source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
inhibit_all_warnings!
#plugin 'cocoapods-pod-sign'
#skip_pod_bundle_sign

def all_pods
  
#  use_modular_headers!
  use_frameworks!
  pod 'AFNetworking', '4.0.1'
  pod 'Masonry', '1.1.0'
  # tips
#  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'SVProgressHUD', '2.2.5'
  pod 'SDWebImage', '4.4.8'
  pod 'SDWebImageAPNGCoder'
  # Model
  pod 'YYModel', '1.0.4'
#  pod 'YYCache', '1.0.4'
  pod 'YYCategories', '1.0.4'
#  pod 'IQKeyboardManager', '6.5.10'

  pod 'LEEAlert', '1.6.4'
  pod 'JXCategoryView', '1.6.1'

  # Byted
#  pod 'BytedEffect', :path => 'bytedEffect.podspec'
#  # Sense
#  pod 'SenseLib', :path => 'sense.podspec'
  # FU
  pod 'fuLib', :path => 'fu.podspec'
  
  pod 'AgoraSyncManager-overseas', '~> 3.0.5'

#  pod 'sdk', :path => 'sdk.podspec'
#  pod 'AgoraRtcEngine_iOS', '~> 4.2.2'
  pod 'AgoraRtcEngine_Special_iOS', '4.1.1.16'

  pod 'VideoLoaderAPI', :path => 'AgoraEntScenarios/Common/API/VideoLoaderAPI'

  #ThirdParty
  pod 'HWWeakTimer', '1.0'
#  pod 'LSTPopView', '0.3.10'
  pod 'SocketRocket', '0.7.0'
  pod 'Agora-Scene-Utils', '1.1.0'
  
#  pod "ScoreEffectUI", '1.0.1'
#  pod 'AgoraLyricsScore', '1.1.1-beta-3'
##  pod 'AgoraLyricsScore', :git => 'https://github.com/AgoraIO-Community/LrcView-iOS.git', :commit => 'cc0951f11f5fa6113ec2b9df2a509efa881d5bd7'
##  pod 'AgoraLyricsScore', :path => '../../AgoraLyricsScore/AgoraLyricsScore.podspec'
#  pod 'AgoraRtm_iOS', '1.5.1'
#  pod 'Zip'
  pod 'MJRefresh'
  
  
  # Swift Code Formatter
#  pod 'SwiftFormat/CLI'

  #VoiceChatRoom rely
  pod 'ZSwiftBaseLib', '0.1.6.1'

  pod 'SnapKit'
  pod 'SVGAPlayer'
  pod 'KakaJSON'
  pod 'Agora_Chat_iOS', '1.0.8'
  pod 'SwiftyBeaver', '1.9.5'
  pod 'Protobuf', '3.22.1'
 #  pod 'LookinServer', :subspecs => ['Swift'], :configurations => ['Debug']

  #need to remove
#  pod 'MJRefresh'
end

target 'AgoraEntScenarios' do
  all_pods
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
#    end
#  end
#end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      shell_script_path = "Pods/Target Support Files/#{target.name}/#{target.name}-frameworks.sh"
      if File::exist?(shell_script_path)
        shell_script_input_lines = File.readlines(shell_script_path)
        shell_script_output_lines = shell_script_input_lines.map { |line| line.sub("source=\"$(readlink \"${source}\")\"", "source=\"$(readlink -f \"${source}\")\"") }
        File.open(shell_script_path, 'w') do |f|
          shell_script_output_lines.each do |line|
            f.write line
          end
        end
      end
    end
  end
end


system("./libs/setup_podspec.sh")
